In [1]:
import datetime as dt
import pandas as pd
from datetime import datetime
from datetime import timedelta, date

In [2]:
dates_list=[]
dates_list_1=[]
# dt start='01-22-2020';
# df finish='03-28-2020';

def daterange(start_date, end_date):
      for n in range(int ((end_date - start_date).days)):
             yield start_date + timedelta(n)
start_date = date(2020, 1, 22)
end_date = date(2020, 3, 22)
for single_date in daterange(start_date, end_date):
    dates_list.append(single_date.strftime("%m-%d-%Y")+'.csv')
print(dates_list)
start_date1 = date(2020, 3, 22)
end_date1 = date(2020, 3, 29)
for each_single_date in daterange(start_date1, end_date1):
    dates_list_1.append(each_single_date.strftime("%m-%d-%Y")+'.csv')
dates_list_1

['01-22-2020.csv', '01-23-2020.csv', '01-24-2020.csv', '01-25-2020.csv', '01-26-2020.csv', '01-27-2020.csv', '01-28-2020.csv', '01-29-2020.csv', '01-30-2020.csv', '01-31-2020.csv', '02-01-2020.csv', '02-02-2020.csv', '02-03-2020.csv', '02-04-2020.csv', '02-05-2020.csv', '02-06-2020.csv', '02-07-2020.csv', '02-08-2020.csv', '02-09-2020.csv', '02-10-2020.csv', '02-11-2020.csv', '02-12-2020.csv', '02-13-2020.csv', '02-14-2020.csv', '02-15-2020.csv', '02-16-2020.csv', '02-17-2020.csv', '02-18-2020.csv', '02-19-2020.csv', '02-20-2020.csv', '02-21-2020.csv', '02-22-2020.csv', '02-23-2020.csv', '02-24-2020.csv', '02-25-2020.csv', '02-26-2020.csv', '02-27-2020.csv', '02-28-2020.csv', '02-29-2020.csv', '03-01-2020.csv', '03-02-2020.csv', '03-03-2020.csv', '03-04-2020.csv', '03-05-2020.csv', '03-06-2020.csv', '03-07-2020.csv', '03-08-2020.csv', '03-09-2020.csv', '03-10-2020.csv', '03-11-2020.csv', '03-12-2020.csv', '03-13-2020.csv', '03-14-2020.csv', '03-15-2020.csv', '03-16-2020.csv', '03-17-2020.csv', '03-18-2020.csv', '03-19-2020.csv', '03-20-2020.csv', '03-21-2020.csv']

['03-22-2020.csv',
 '03-23-2020.csv',
 '03-24-2020.csv',
 '03-25-2020.csv',
 '03-26-2020.csv',
 '03-27-2020.csv',
 '03-28-2020.csv']

In [23]:
init_path='csse_covid_19_daily_reports/'+dates_list[0]
init_date_df=pd.read_csv(init_path)
for each_date in dates_list[1:]:
    loop_date_path='csse_covid_19_daily_reports/'+each_date
    new_date_df=pd.read_csv(loop_date_path)
    init_date_df=pd.concat([init_date_df, new_date_df], axis=0, sort=True)

covid_start_df=init_date_df.rename(columns={"Country/Region":"Country_Region","Last Update":"Last_Update","Latitude":"Lat","Longitude":"Long_","Province/State":"Province_State"})
covid_start_df

,Confirmed,Country_Region,Deaths,Last_Update,Lat,Long_,Province_State,Recovered
0,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Anhui,NaN
1,14.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Beijing,NaN
2,6.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Chongqing,NaN
3,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Fujian,NaN
4,NaN,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Gansu,NaN
...,...,...,...,...,...,...,...,...
299,0.0,Jersey,0.0,2020-03-17T18:33:03,49.1900,-2.110,NaN,0.0
300,0.0,Puerto Rico,0.0,2020-03-17T16:13:14,18.2000,-66.500,NaN,0.0
301,0.0,Republic of the Congo,0.0,2020-03-17T21:33:03,-1.4400,15.556,NaN,0.0
302,0.0,The Bahamas,0.0,2020-03-19T12:13:38,24.2500,-76.000,NaN,0.0
303,0.0,The Gambia,0.0,2020-03-18T14:13:56,13.4667,-16.600,NaN,0.0

In [24]:
init_path_1='csse_covid_19_daily_reports/'+dates_list_1[0]
init_date_df_1=pd.read_csv(init_path_1)
for each_date in dates_list_1[1:]:
    loop_date_path_1='csse_covid_19_daily_reports/'+each_date
    new_date_df_1=pd.read_csv(loop_date_path_1)
    init_date_df_1=pd.concat([init_date_df_1, new_date_df_1], axis=0, sort=True)
init_date_df_1
init_date_df_2=init_date_df_1.drop(['Active','Admin2','Combined_Key','FIPS'], axis=1)
init_date_df_2

,Confirmed,Country_Region,Deaths,Last_Update,Lat,Long_,Province_State,Recovered
0,9654,US,63,3/22/20 23:45,40.767273,-73.971526,New York,0
1,1900,US,4,3/22/20 23:45,40.740665,-73.589419,New York,0
2,1873,US,0,3/22/20 23:45,41.162784,-73.757417,New York,0
3,1034,US,9,3/22/20 23:45,40.883201,-72.801217,New York,0
4,455,US,1,3/22/20 23:45,41.150279,-74.025605,New York,0
...,...,...,...,...,...,...,...,...
3425,119,Venezuela,2,2020-03-28 23:05:25,6.423800,-66.589700,NaN,39
3426,174,Vietnam,0,2020-03-28 23:05:25,14.058324,108.277199,NaN,21
3427,98,West Bank and Gaza,1,2020-03-28 23:05:25,31.952200,35.233200,NaN,18
3428,28,Zambia,0,2020-03-28 23:05:25,-13.133897,27.849332,NaN,0
3429,7,Zimbabwe,1,2020-03-28 23:05:25,-19.015438,29.154857,NaN,0

In [34]:
combine_df = pd.concat([covid_start_df,init_date_df_2], axis=0)
combine_df

,Confirmed,Country_Region,Deaths,Last_Update,Lat,Long_,Province_State,Recovered
0,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Anhui,NaN
1,14.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Beijing,NaN
2,6.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Chongqing,NaN
3,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Fujian,NaN
4,NaN,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Gansu,NaN
...,...,...,...,...,...,...,...,...
3425,119.0,Venezuela,2.0,2020-03-28 23:05:25,6.423800,-66.589700,NaN,39.0
3426,174.0,Vietnam,0.0,2020-03-28 23:05:25,14.058324,108.277199,NaN,21.0
3427,98.0,West Bank and Gaza,1.0,2020-03-28 23:05:25,31.952200,35.233200,NaN,18.0
3428,28.0,Zambia,0.0,2020-03-28 23:05:25,-13.133897,27.849332,NaN,0.0
3429,7.0,Zimbabwe,1.0,2020-03-28 23:05:25,-19.015438,29.154857,NaN,0.0

In [25]:
# combine_df=pd.concat([covid_start_df,init_date_df_2],axis=1,sort=False)
# combine_df
# init_date_df.set_index(['Country/Region', 'Province/State'], inplace=True)
# init_date_df_update.set_index(['Country/Region', 'Province/State'], inplace=True)
# init_date_df.set_index(['Country/Region', 'Province/State'], inplace=True)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [35]:
combine_df

combine_df_US=combine_df.loc[combine_df['Country_Region'] == 'US']
NY=combine_df_US[combine_df_US['Province_State']=="New York"]
NJ=combine_df_US[combine_df_US['Province_State']=="New Jersey"]
CA=combine_df_US[combine_df_US['Province_State']=="California"]
MI=combine_df_US[combine_df_US['Province_State']=="Michigan"]
WA=combine_df_US[combine_df_US['Province_State']=="Washington"]
FL=combine_df_US[combine_df_US['Province_State']=="Florida"]
print(NY)
print(NJ)
print(CA)
print(MI)
print(WA)
print(FL)

      Confirmed Country_Region  Deaths          Last_Update        Lat  \
36        173.0             US     0.0  2020-03-10T17:13:27  42.165700
36        220.0             US     0.0  2020-03-11T22:53:03  42.165700
29        328.0             US     0.0  2020-03-12T21:39:10  42.165700
203       421.0             US     0.0  2020-03-11T20:00:00  42.165726
28        525.0             US     2.0  2020-03-14T22:13:32  42.165700
...         ...            ...     ...                  ...        ...
2995        9.0             US     0.0  2020-03-28 23:05:37  43.311538
3025       12.0             US     0.0  2020-03-28 23:05:37  43.154944
3050     7875.0             US    10.0  2020-03-28 23:05:37  41.162784
3138        7.0             US     1.0  2020-03-28 23:05:37  42.701451
3149        0.0             US     0.0  2020-03-28 23:05:37  42.635055

          Long_ Province_State  Recovered
36   -74.948100       New York        0.0
36   -74.948100       New York        0.0
29   -74.948100       New York        0.0
203  -74.948051       New York        0.0
28   -74.948100       New York        0.0
...         ...            ...        ...
2995 -73.430434       New York        0.0
3025 -77.029765       New York        0.0
3050 -73.757417       New York        0.0
3138 -78.221996       New York        0.0
3149 -77.103699       New York        0.0

[453 rows x 8 columns]
      Confirmed Country_Region  Deaths          Last_Update        Lat  \
96         15.0             US     1.0  2020-03-10T18:13:16  40.298900
87         23.0             US     1.0  2020-03-11T18:52:04  40.298900
86         29.0             US     1.0  2020-03-12T21:39:10  40.298900
201        29.0             US     1.0  2020-03-11T20:00:00  40.298904
82         69.0             US     1.0  2020-03-14T22:13:32  40.298900
...         ...            ...     ...                  ...        ...
2639      258.0             US     4.0  2020-03-28 23:05:37  40.564657
2744       81.0             US     0.0  2020-03-28 23:05:37  41.138916
2870     2478.0             US    86.0  2020-03-28 23:05:37   0.000000
2887      742.0             US     0.0  2020-03-28 23:05:37  40.658354
2964       51.0             US     0.0  2020-03-28 23:05:37  40.859518

          Long_ Province_State  Recovered
96   -74.521000     New Jersey        0.0
87   -74.521000     New Jersey        0.0
86   -74.521000     New Jersey        0.0
201  -74.521011     New Jersey        0.0
82   -74.521000     New Jersey        0.0
...         ...            ...        ...
2639 -74.616830     New Jersey        0.0
2744 -74.691182     New Jersey        0.0
2870   0.000000     New Jersey        0.0
2887 -74.306801     New Jersey        0.0
2964 -74.995565     New Jersey        0.0

[166 rows x 8 columns]
      Confirmed Country_Region  Deaths          Last_Update        Lat  \
35          2.0             US     NaN        1/26/20 16:00        NaN
35          2.0             US     NaN        1/27/20 23:59        NaN
35          2.0             US     NaN        1/28/20 23:00        NaN
35          2.0             US     NaN        1/29/20 19:30        NaN
36          2.0             US     NaN        1/30/20 16:00        NaN
...         ...            ...     ...                  ...        ...
2837       24.0             US     0.0  2020-03-28 23:05:37  36.220266
2840        0.0             US     0.0  2020-03-28 23:05:37  38.026440
2917       83.0             US     3.0  2020-03-28 23:05:37  34.444657
3156       16.0             US     1.0  2020-03-28 23:05:37  38.682789
3163        3.0             US     0.0  2020-03-28 23:05:37  39.262559

           Long_ Province_State  Recovered
35           NaN     California        NaN
35           NaN     California        NaN
35           NaN     California        NaN
35           NaN     California        NaN
36           NaN     California        NaN
...          ...            ...        ...
2837 -118.802020     California        0.0
2840 -119.952509     California        0.0
2917 -119.091061     California        0.0
3156 -121.901829     California        0.0
3163 -121.353564     California        0.0

[425 rows x 8 columns]
      Confirmed Country_Region  Deaths          Last_Update        Lat  \
198         0.0             US     0.0  2020-03-10T02:33:04  43.326600
175         2.0             US     0.0  2020-03-11T03:33:05  43.326600
180         2.0             US     0.0  2020-03-11T03:33:05  43.326600
193        16.0             US     0.0  2020-03-11T20:00:00  43.326618
123        25.0             US     0.0  2020-03-14T16:53:03  43.326600
...         ...            ...     ...                  ...        ...
2868       47.0             US     0.0  2020-03-28 23:05:37   0.000000
2910        4.0             US     0.0  2020-03-28 23:05:37  42.251902
3010      185.0             US     3.0  2020-03-28 23:05:37  42.253105
3021     2316.0             US    46.0  2020-03-28 23:05:37  42.280984
3055        1.0             US     0.0  2020-03-28 23:05:37  44.338536

          Long_ Province_State  Recovered
198  -84.536100       Michigan        0.0
175  -84.536100       Michigan        0.0
180  -84.536100       Michigan        0.0
193  -84.536095       Michigan        0.0
123  -84.536100       Michigan        0.0
...         ...            ...        ...
2868   0.000000       Michigan        0.0
2910 -86.019391       Michigan        0.0
3010 -83.838532       Michigan        0.0
3021 -83.281255       Michigan        0.0
3055 -85.577127       Michigan        0.0

[600 rows x 8 columns]
      Confirmed Country_Region  Deaths          Last_Update        Lat  \
31          1.0             US     NaN      1/22/2020 17:00        NaN
31          1.0             US     NaN        1/23/20 17:00        NaN
33          1.0             US     NaN        1/24/20 17:00        NaN
33          1.0             US     NaN        1/25/20 17:00        NaN
33          1.0             US     NaN        1/26/20 16:00        NaN
...         ...            ...     ...                  ...        ...
2936        0.0             US     0.0  2020-03-28 23:05:37  46.291800
2943        4.0             US     0.0  2020-03-28 23:05:37  46.230401
3057      102.0             US     4.0  2020-03-28 23:05:37  48.822280
3073        6.0             US     0.0  2020-03-28 23:05:37  46.900225
3143       82.0             US     2.0  2020-03-28 23:05:37  46.457385

           Long_ Province_State  Recovered
31           NaN     Washington        NaN
31           NaN     Washington        NaN
33           NaN     Washington        NaN
33           NaN     Washington        NaN
33           NaN     Washington        NaN
...          ...            ...        ...
2936 -123.425083     Washington        0.0
2943 -118.477554     Washington        0.0
3057 -121.749002     Washington        0.0
3073 -117.524176     Washington        0.0
3143 -120.738013     Washington        0.0

[304 rows x 8 columns]
      Confirmed Country_Region  Deaths          Last_Update        Lat  \
95         15.0             US     2.0  2020-03-10T13:13:14  27.766300
82         28.0             US     2.0  2020-03-11T03:33:05  27.766300
82         35.0             US     2.0  2020-03-12T21:39:10  27.766300
180        50.0             US     2.0  2020-03-11T20:00:00  27.766279
79         76.0             US     3.0  2020-03-14T18:53:03  27.766300
...         ...            ...     ...                  ...        ...
2879        0.0             US     0.0  2020-03-28 23:05:37  30.044130
2929       44.0             US     0.0  2020-03-28 23:05:37  29.058589
2938        0.0             US     0.0  2020-03-28 23:05:37  30.165489
2949       15.0             US     0.0  2020-03-28 23:05:37  30.642040
2980        1.0             US     0.0  2020-03-28 23:05:37  30.613593

          Long_ Province_State  Recovered
95   -81.686800        Florida        0.0
82   -81.686800        Florida        0.0
82   -81.686800        Florida        0.0
180  -81.686783        Florida        0.0
79   -81.686800        Florida        0.0
...         ...            ...        ...
2879 -82.374974        Florida        0.0
2929 -81.182633        Florida        0.0
2938 -84.398952        Florida        0.0
2949 -86.169357        Florida        0.0
2980 -85.660025        Florida        0.0

[486 rows x 8 columns]

In [36]:
NY_locations = NY[["Lat", "Long_"]]
NJ_locations = NJ[["Lat", "Long_"]]
CA_locations = CA[["Lat", "Long_"]]
MI_locations = MI[["Lat", "Long_"]]
WA_locations = WA[["Lat", "Long_"]]
FL_locations = FL[["Lat", "Long_"]]

In [39]:
from IPython.display import display
import ipywidgets as widgets

import gmaps
# gmaps.configure(api_key='')
class AcledExplorer(object):
    """
    Jupyter widget for exploring the ACLED dataset.

    The user uses the slider to choose a year. This renders
    a heatmap of civilian victims in that year.
    """

In [ ]:
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)